spin_version = "1"
authors = ["Raymundo Vásquez Ruiz <raymundo.vr@protonmail.com>"]
description = "A webscraper using Spin"
name = "webscraper"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "webscraper"
source = "target/wasm32-wasi/release/webscraper.wasm"
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
